In [1]:
#pip install matplotlib

In [2]:
import streamlit as st
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error, accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.neighbors import KNeighborsRegressor
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=sns.load_dataset("iris")
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
le = LabelEncoder()
data['species'] = le.fit_transform(data['species'])

In [5]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:
X = data.iloc[ :, : -1].values
Y= data.iloc[ :,  -1].values

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [8]:
model= Sequential()

In [9]:
model.add(InputLayer(shape =  (4,)))
model.add(Dense(20, activation = 'relu'))
model.add(Dense(15, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(8, activation = 'relu'))
model.add(Dense(3, activation = 'softmax'))

In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 20)             │           100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │           315 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │            88 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 690 (2.70 KB)

 Trainable params: 690 (2.70 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.compile( optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [12]:
model.fit( X_train, y_train,  verbose=1,  epochs=100,  validation_data=(X_test, y_test), callbacks=EarlyStopping(patience=5))

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 78ms/step - accuracy: 0.0500 - loss: 1.1495 - val_accuracy: 0.3000 - val_loss: 1.1461
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.1333 - loss: 1.1258 - val_accuracy: 0.3000 - val_loss: 1.1264
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1833 - loss: 1.1098 - val_accuracy: 0.3000 - val_loss: 1.1067
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.2667 - loss: 1.0946 - val_accuracy: 0.3333 - val_loss: 1.0895
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.3167 - loss: 1.0815 - val_accuracy: 0.3333 - val_loss: 1.0725
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3333 - loss: 1.0676 - val_accuracy: 0.3333 - val_loss: 1.0555
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4667 - loss: 1.0552 - val_accuracy: 0.6667 - val_loss: 1.0448
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6583 - loss: 1.0475 - val_accuracy: 0.7000 - val_loss: 1.0350
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6167 - loss: 1.0328 - val_accuracy: 0.5000 - val_loss: 1.0245
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.3750 - loss: 1.0208 - val_accuracy: 0.4000 - val_loss: 1.0169
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4250 - loss: 1.0081 - val_accuracy: 0.5333 - val_loss: 1.0047
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4833 - loss: 0.9965 - val_accuracy: 0.5333 - val_loss: 0.9935
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.9851 - val_accuracy: 0.5667 - val_loss: 0.9841
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6167 - loss: 0.9752 - val_accuracy: 0.5667 - val_loss: 0.9738
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6083 - loss: 0.9638 - val_accuracy: 0.5333 - val_loss: 0.9619
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5833 - loss: 0.9509 - val_accuracy: 0.5333 - val_loss: 0.9496
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5667 - loss: 0.9382 - val_accuracy: 0.5667 - val_loss: 0.9352
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6250 - loss: 0.9228 - val_accuracy: 0.6333 - val_loss: 0.9198
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6583 - loss: 0.9068 - val_accuracy: 0.7000 - val_loss: 0.9036
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6583 - loss: 0.8908 - val_accuracy: 0.7000 - val_loss: 0.8828
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6833 - loss: 0.8694 - val_accuracy: 0.8000 - val_loss: 0.8572
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.8000 - loss: 0.8412 - val_accuracy: 0.6333 - val_loss: 0.8238
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.7917 - loss: 0.8026 - val_accuracy: 0.6333 - val_loss: 0.7843
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6750 - loss: 0.7616 - val_accuracy: 0.6333 - val_loss: 0.7485
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.6750 - loss: 0.7210 - val_accuracy: 0.6333 - val_loss: 0.7157
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6750 - loss: 0.6830 - val_accuracy: 0.6333 - val_loss: 0.6876
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6750 - loss: 0.6512 - val_accuracy: 0.6333 - val_loss: 0.6596
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6750 - loss: 0.6198 - val_accuracy: 0.6333 - val_loss: 0.6314
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6750 - loss: 0.5974 - val_accuracy: 0.6333 - val_loss: 0.6124
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6750 - loss: 0.5758 - val_accuracy: 0.6333 - val_loss: 0.5933
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6750 - loss: 0.5571 - val_accuracy: 0.6333 - val_loss: 0.5764
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6750 - loss: 0.5395 - val_accuracy: 0.6333 - val_loss: 0.5605
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6750 - loss: 0.5232 - val_accuracy: 0.6333 - val_loss: 0.5453
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6750 - loss: 0.5084 - val_accuracy: 0.6333 - val_loss: 0.5294
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6750 - loss: 0.4943 - val_accuracy: 0.6333 - val_loss: 0.5150
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.6833 - loss: 0.4798 - val_accuracy: 0.6333 - val_loss: 0.5000
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.4668 - val_accuracy: 0.7333 - val_loss: 0.4854
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8500 - loss: 0.4537 - val_accuracy: 0.8000 - val_loss: 0.4727
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.8833 - loss: 0.4421 - val_accuracy: 0.8000 - val_loss: 0.4593
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9333 - loss: 0.4307 - val_accuracy: 0.8667 - val_loss: 0.4471
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9583 - loss: 0.4194 - val_accuracy: 0.8667 - val_loss: 0.4351
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9583 - loss: 0.4086 - val_accuracy: 0.8333 - val_loss: 0.4241
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9583 - loss: 0.3985 - val_accuracy: 0.8667 - val_loss: 0.4144
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9583 - loss: 0.3876 - val_accuracy: 0.8667 - val_loss: 0.4061
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9750 - loss: 0.3782 - val_accuracy: 0.8667 - val_loss: 0.3979
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9750 - loss: 0.3679 - val_accuracy: 0.8667 - val_loss: 0.3863
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9667 - loss: 0.3574 - val_accuracy: 0.8667 - val_loss: 0.3756
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9750 - loss: 0.3476 - val_accuracy: 0.8667 - val_loss: 0.3659
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9750 - loss: 0.3390 - val_accuracy: 0.9333 - val_loss: 0.3568
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9750 - loss: 0.3265 - val_accuracy: 0.8667 - val_loss: 0.3453
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9667 - loss: 0.3174 - val_accuracy: 0.8667 - val_loss: 0.3356
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9750 - loss: 0.3063 - val_accuracy: 0.9667 - val_loss: 0.3261
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9833 - loss: 0.2947 - val_accuracy: 0.9667 - val_loss: 0.3167
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9750 - loss: 0.2846 - val_accuracy: 0.8667 - val_loss: 0.3076
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9750 - loss: 0.2727 - val_accuracy: 0.9333 - val_loss: 0.2979
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9750 - loss: 0.2627 - val_accuracy: 0.9667 - val_loss: 0.2892
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9750 - loss: 0.2517 - val_accuracy: 0.9000 - val_loss: 0.2799
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9750 - loss: 0.2439 - val_accuracy: 0.8667 - val_loss: 0.2713
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9750 - loss: 0.2307 - val_accuracy: 0.9667 - val_loss: 0.2600
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9833 - loss: 0.2250 - val_accuracy: 0.9667 - val_loss: 0.2491
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.2128 - val_accuracy: 0.9333 - val_loss: 0.2411
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9750 - loss: 0.2040 - val_accuracy: 0.9333 - val_loss: 0.2343
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9750 - loss: 0.1952 - val_accuracy: 0.9333 - val_loss: 0.2266
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9833 - loss: 0.1878 - val_accuracy: 0.9667 - val_loss: 0.2189
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9833 - loss: 0.1817 - val_accuracy: 0.9333 - val_loss: 0.2137
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.9750 - loss: 0.1742 - val_accuracy: 0.9333 - val_loss: 0.2073
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9833 - loss: 0.1675 - val_accuracy: 0.9667 - val_loss: 0.2004
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.1635 - val_accuracy: 0.9667 - val_loss: 0.1939
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9833 - loss: 0.1561 - val_accuracy: 0.9333 - val_loss: 0.1921
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9750 - loss: 0.1532 - val_accuracy: 0.9333 - val_loss: 0.1874
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9750 - loss: 0.1483 - val_accuracy: 0.9667 - val_loss: 0.1803
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.1426 - val_accuracy: 0.9333 - val_loss: 0.1785
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9750 - loss: 0.1392 - val_accuracy: 0.9333 - val_loss: 0.1753
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9750 - loss: 0.1367 - val_accuracy: 0.9667 - val_loss: 0.1675
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9833 - loss: 0.1315 - val_accuracy: 0.9333 - val_loss: 0.1669
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9667 - loss: 0.1290 - val_accuracy: 0.9333 - val_loss: 0.1695
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9750 - loss: 0.1308 - val_accuracy: 0.9667 - val_loss: 0.1581
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9833 - loss: 0.1220 - val_accuracy: 0.9667 - val_loss: 0.1574
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9667 - loss: 0.1203 - val_accuracy: 0.9000 - val_loss: 0.1627
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9667 - loss: 0.1188 - val_accuracy: 0.9333 - val_loss: 0.1559
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9833 - loss: 0.1136 - val_accuracy: 0.9667 - val_loss: 0.1472
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9833 - loss: 0.1162 - val_accuracy: 0.9667 - val_loss: 0.1448
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9833 - loss: 0.1122 - val_accuracy: 0.9333 - val_loss: 0.1517
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9667 - loss: 0.1106 - val_accuracy: 0.9333 - val_loss: 0.1503
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9833 - loss: 0.1107 - val_accuracy: 0.9667 - val_loss: 0.1375
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9833 - loss: 0.1075 - val_accuracy: 0.9333 - val_loss: 0.1416
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9750 - loss: 0.1050 - val_accuracy: 0.9333 - val_loss: 0.1428
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9833 - loss: 0.1017 - val_accuracy: 0.9667 - val_loss: 0.1333
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9833 - loss: 0.1011 - val_accuracy: 0.9667 - val_loss: 0.1327
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9833 - loss: 0.0983 - val_accuracy: 0.9333 - val_loss: 0.1362
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9667 - loss: 0.0989 - val_accuracy: 0.9333 - val_loss: 0.1375
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9750 - loss: 0.0962 - val_accuracy: 0.9667 - val_loss: 0.1276
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.0958 - val_accuracy: 0.9667 - val_loss: 0.1279
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.0939 - val_accuracy: 0.9333 - val_loss: 0.1332
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9750 - loss: 0.0926 - val_accuracy: 0.9333 - val_loss: 0.1295
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.0907 - val_accuracy: 0.9667 - val_loss: 0.1248
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9833 - loss: 0.0912 - val_accuracy: 0.9667 - val_loss: 0.1233
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9833 - loss: 0.0905 - val_accuracy: 0.9667 - val_loss: 0.1236
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9833 - loss: 0.0882 - val_accuracy: 0.8667 - val_loss: 0.1374
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9667 - loss: 0.0901 - val_accuracy: 0.9333 - val_loss: 0.1268

In [13]:
history = model.history

In [14]:
history.history

{'accuracy': [0.05000000074505806,
  0.13333334028720856,
  0.18333333730697632,
  0.2666666805744171,
  0.3166666626930237,
  0.3333333432674408,
  0.46666666865348816,
  0.6583333611488342,
  0.6166666746139526,
  0.375,
  0.42500001192092896,
  0.4833333194255829,
  0.5833333134651184,
  0.6166666746139526,
  0.6083333492279053,
  0.5833333134651184,
  0.5666666626930237,
  0.625,
  0.6583333611488342,
  0.6583333611488342,
  0.6833333373069763,
  0.800000011920929,
  0.7916666865348816,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.675000011920929,
  0.6833333373069763,
  0.75,
  0.8500000238418579,
  0.8833333253860474,
  0.9333333373069763,
  0.9583333134651184,
  0.9583333134651184,
  0.9583333134651184,
  0.9583333134651184,
  0.9750000238418579,
  0.9750000238418579,
  0.9666666388511658,
  0.9750000238418579,
  0.9750000238418579,
  0.9750000238418579,
  0.9666666388511658,
  0.9750000238418579,
  0.9833333492279053,
  0.9750000238418579,
  0.9750000238418579,
  0.9750000238418579,
  0.9750000238418579,
  0.9750000238418579,
  0.9750000238418579,
  0.9833333492279053,
  0.9833333492279053,
  0.9750000238418579,
  0.9750000238418579,
  0.9833333492279053,
  0.9833333492279053,
  0.9750000238418579,
  0.9833333492279053,
  0.9833333492279053,
  0.9833333492279053,
  0.9750000238418579,
  0.9750000238418579,
  0.9833333492279053,
  0.9750000238418579,
  0.9750000238418579,
  0.9833333492279053,
  0.9666666388511658,
  0.9750000238418579,
  0.9833333492279053,
  0.9666666388511658,
  0.9666666388511658,
  0.9833333492279053,
  0.9833333492279053,
  0.9833333492279053,
  0.9666666388511658,
  0.9833333492279053,
  0.9833333492279053,
  0.9750000238418579,
  0.9833333492279053,
  0.9833333492279053,
  0.9833333492279053,
  0.9666666388511658,
  0.9750000238418579,
  0.9833333492279053,
  0.9833333492279053,
  0.9750000238418579,
  0.9833333492279053,
  0.9833333492279053,
  0.9833333492279053,
  0.9833333492279053,
  0.9666666388511658],
 'loss': [1.1495099067687988,
  1.1257766485214233,
  1.1098129749298096,
  1.0945626497268677,
  1.0815180540084839,
  1.0675795078277588,
  1.055230736732483,
  1.0475245714187622,
  1.0327507257461548,
  1.0207597017288208,
  1.0081218481063843,
  0.9965182542800903,
  0.9851254820823669,
  0.9752269387245178,
  0.9637798070907593,
  0.9508705139160156,
  0.9381746053695679,
  0.9228463768959045,
  0.9067605137825012,
  0.890796959400177,
  0.8693637251853943,
  0.8411842584609985,
  0.8025532960891724,
  0.7616136074066162,
  0.7209566831588745,
  0.6830103993415833,
  0.6512270569801331,
  0.6198408007621765,
  0.597369372844696,
  0.5758237838745117,
  0.5570892095565796,
  0.5395192503929138,
  0.523226261138916,
  0.5083761811256409,
  0.4943024814128876,
  0.4798082113265991,
  0.46676746010780334,
  0.4536554515361786,
  0.4420778155326843,
  0.4306742250919342,
  0.4193982779979706,
  0.40858128666877747,
  0.3985118269920349,
  0.38763439655303955,
  0.37824147939682007,
  0.36789146065711975,
  0.35737544298171997,
  0.3475502133369446,
  0.3390210270881653,
  0.326523095369339,
  0.31736552715301514,
  0.3062664568424225,
  0.29468199610710144,
  0.28463250398635864,
  0.2726575434207916,
  0.2626713812351227,
  0.2517460882663727,
  0.24387769401073456,
  0.23071856796741486,
  0.2250424325466156,
  0.2127716988325119,
  0.20404008030891418,
  0.19522619247436523,
  0.18780913949012756,
  0.18168893456459045,
  0.1742105931043625,
  0.1675373762845993,
  0.16353467106819153,
  0.15610842406749725,
  0.15315556526184082,
  0.14832989871501923,
  0.1425577998161316,
  0.13920950889587402,
  0.1367485374212265,
  0.13152191042900085,
  0.12899862229824066,
  0.13080590963363647,
  0.12202200293540955,
  0.12030588835477829,
  0.11876378953456879,
  0.11362817883491516,
  0.11624947190284729,
  0.11215832829475403,
  0.1105724647641182,
  0.1106516495347023,
  0.10746626555919647,
  0.10499810427427292,
  0.10172189027070999,
  0.10109470784664154,
  0.09831716120243073,
  0.09886865317821503,
  0.09622962027788162,
  0.09583953768014908,
  0.09391205757856369,
  0.09264656901359558,
  0.09067940711975098,
  0.09118077158927917,
  0.09045009315013885,
  0.08823927491903305,
  0.0900973528623581],
 'val_accuracy': [0.30000001192092896,
  0.30000001192092896,
  0.30000001192092896,
  0.3333333432674408,
  0.3333333432674408,
  0.3333333432674408,
  0.6666666865348816,
  0.699999988079071,
  0.5,
  0.4000000059604645,
  0.5333333611488342,
  0.5333333611488342,
  0.5666666626930237,
  0.5666666626930237,
  0.5333333611488342,
  0.5333333611488342,
  0.5666666626930237,
  0.6333333253860474,
  0.699999988079071,
  0.699999988079071,
  0.800000011920929,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.6333333253860474,
  0.7333333492279053,
  0.800000011920929,
  0.800000011920929,
  0.8666666746139526,
  0.8666666746139526,
  0.8333333134651184,
  0.8666666746139526,
  0.8666666746139526,
  0.8666666746139526,
  0.8666666746139526,
  0.8666666746139526,
  0.8666666746139526,
  0.9333333373069763,
  0.8666666746139526,
  0.8666666746139526,
  0.9666666388511658,
  0.9666666388511658,
  0.8666666746139526,
  0.9333333373069763,
  0.9666666388511658,
  0.8999999761581421,
  0.8666666746139526,
  0.9666666388511658,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9666666388511658,
  0.8999999761581421,
  0.9333333373069763,
  0.9666666388511658,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9666666388511658,
  0.9333333373069763,
  0.9333333373069763,
  0.9666666388511658,
  0.9666666388511658,
  0.9666666388511658,
  0.8666666746139526,
  0.9333333373069763],
 'val_loss': [1.146085500717163,
  1.1264457702636719,
  1.1067216396331787,
  1.0895007848739624,
  1.0724730491638184,
  1.0554994344711304,
  1.0448079109191895,
  1.0349897146224976,
  1.0244501829147339,
  1.0169011354446411,
  1.0047004222869873,
  0.9935298562049866,
  0.9840787649154663,
  0.9737650752067566,
  0.9618833065032959,
  0.949550986289978,
  0.9352109432220459,
  0.9197753667831421,
  0.9035702347755432,
  0.882769763469696,
  0.8572209477424622,
  0.8238078951835632,
  0.7842826843261719,
  0.7485120892524719,
  0.71571946144104,
  0.687604546546936,
  0.6596162915229797,
  0.6313979029655457,
  0.6124138236045837,
  0.5933398604393005,
  0.576377809047699,
  0.5605134963989258,
  0.5452673435211182,
  0.5293968319892883,
  0.5150078535079956,
  0.500017523765564,
  0.48544415831565857,
  0.4726651906967163,
  0.4592897593975067,
  0.447143018245697,
  0.4351275861263275,
  0.4240660071372986,
  0.4143730401992798,
  0.40613582730293274,
  0.39789697527885437,
  0.3863382637500763,
  0.37562793493270874,
  0.36593925952911377,
  0.35676684975624084,
  0.3453049957752228,
  0.3355560898780823,
  0.3260931968688965,
  0.31665802001953125,
  0.30763769149780273,
  0.2978774309158325,
  0.2891903817653656,
  0.27993372082710266,
  0.2712968587875366,
  0.2600368857383728,
  0.24908527731895447,
  0.24107728898525238,
  0.23426590859889984,
  0.22656787931919098,
  0.21894487738609314,
  0.21370291709899902,
  0.20732468366622925,
  0.20041237771511078,
  0.1939014345407486,
  0.19213366508483887,
  0.18741348385810852,
  0.18034008145332336,
  0.17845872044563293,
  0.1753278374671936,
  0.16745930910110474,
  0.1669408529996872,
  0.16951021552085876,
  0.15813149511814117,
  0.15741075575351715,
  0.16267862915992737,
  0.15585239231586456,
  0.14721056818962097,
  0.14481011033058167,
  0.15166912972927094,
  0.15026937425136566,
  0.1375310719013214,
  0.14161933958530426,
  0.14278779923915863,
  0.1332734376192093,
  0.132709801197052,
  0.13616794347763062,
  0.13749098777770996,
  0.12761236727237701,
  0.12794743478298187,
  0.1332271844148636,
  0.12949460744857788,
  0.12475298345088959,
  0.12330023944377899,
  0.12357399612665176,
  0.13740992546081543,
  0.12677711248397827]}

In [15]:
plt.plot(data["sepal_length"] , data[ 'petal_length'])
plt.show()

In [16]:
plt.plot(history.history["accuracy"])

In [17]:
plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])
plt.legend(['acc', 'val_acc'])
plt.show()

In [18]:
plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])
plt.legend(['acc', 'val_acc'])
plt.show()

In [19]:
ypred= model.predict(X_test)
ypred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step

array([[1.5562131e-03, 9.4062293e-01, 5.7820879e-02],
       [9.9631518e-01, 3.6848653e-03, 2.5360011e-12],
       [9.4676622e-09, 2.0598114e-02, 9.7940195e-01],
       [1.0427978e-03, 9.1439193e-01, 8.4565282e-02],
       [1.0009846e-03, 9.4960183e-01, 4.9397111e-02],
       [9.9382281e-01, 6.1771385e-03, 2.2816233e-11],
       [2.4047457e-02, 9.7435570e-01, 1.5969161e-03],
       [7.1745471e-06, 2.1513259e-01, 7.8486019e-01],
       [1.0870163e-04, 3.9095217e-01, 6.0893917e-01],
       [1.0853194e-02, 9.8334092e-01, 5.8059292e-03],
       [4.0242307e-05, 4.4413421e-01, 5.5582553e-01],
       [9.9147850e-01, 8.5215382e-03, 1.5213333e-10],
       [9.9630404e-01, 3.6959331e-03, 2.7594118e-12],
       [9.9208707e-01, 7.9129152e-03, 1.0624138e-10],
       [9.9550337e-01, 4.4966331e-03, 6.1012315e-12],
       [1.3388902e-03, 9.7126442e-01, 2.7396703e-02],
       [1.2050366e-07, 2.1134155e-02, 9.7886568e-01],
       [8.4145023e-03, 9.7748929e-01, 1.4096237e-02],
       [1.3375264e-03, 9.0197527e-01, 9.6687257e-02],
       [1.5270565e-07, 2.3187293e-02, 9.7681260e-01],
       [9.8951250e-01, 1.0487468e-02, 2.5524297e-10],
       [7.0663467e-05, 4.5123190e-01, 5.4869741e-01],
       [9.9089009e-01, 9.1098864e-03, 1.0213061e-10],
       [1.8309541e-07, 2.3158737e-02, 9.7684109e-01],
       [1.2675127e-05, 5.3241014e-01, 4.6757725e-01],
       [1.0904429e-06, 6.5122329e-02, 9.3487656e-01],
       [2.1506642e-07, 2.3759022e-02, 9.7624069e-01],
       [7.5246902e-08, 1.7068818e-02, 9.8293108e-01],
       [9.8909050e-01, 1.0909513e-02, 3.2459208e-10],
       [9.8909187e-01, 1.0908061e-02, 3.0122915e-10]], dtype=float32)

In [20]:
ypred = np.argmax(ypred, axis=1)
ypred

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 1, 2, 2, 2, 0, 0])

In [21]:
accuracy_score(y_test, ypred)

0.9333333333333333

In [22]:
print(classification_report(y_test, ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      0.89      0.89         9
           2       0.91      0.91      0.91        11

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30